# Generated by Django 5.2.17 on 2026-09-20 02:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("empleado", "0001_initial"),
        ("liquidacion", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="LiquidacionEmpleado",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("remunerativo", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "no_remunerativo",
                    models.DecimalField(decimal_places=2, max_digits=12),
                ),
                ("bruto", models.DecimalField(decimal_places=2, max_digits=12)),
                ("descuentos", models.DecimalField(decimal_places=2, max_digits=12)),
                ("neto", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "contribuciones",
                    models.DecimalField(decimal_places=2, max_digits=12),
                ),
                ("costo_laboral", models.DecimalField(decimal_places=2, max_digits=12)),
                ("categoria", models.CharField(max_length=255)),
                ("banco_de_cobro", models.CharField(max_length=255)),
                (
                    "empleado",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="liquidaciones",
                        to="empleado.empleado",
                    ),
                ),
                (
                    "liquidacion",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="empleados",
                        to="liquidacion.liquidacion",
                    ),
                ),
            ],
            options={
                "verbose_name": "liquidación por empleado",
                "verbose_name_plural": "liquidación por empleado",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("liquidacion", "empleado"),
                        name="unique_empleado_por_liquidacion",
                    )
                ],
            },
        ),
    ]
