# Generated by Django 5.2.17 on 2026-09-20 02:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("empresa", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Liquidacion",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("periodo", models.DateField()),
                ("fecha_pago", models.DateField()),
                (
                    "estado",
                    models.CharField(
                        choices=[("borrador", "Borrador"), ("cerrada", "Cerrada")],
                        max_length=30,
                    ),
                ),
                (
                    "domicilio_empresa",
                    models.CharField(
                        help_text="Domicilio de la empresa al momento de realizar la liquidación.",
                        max_length=255,
                    ),
                ),
                (
                    "empresa",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="liquidaciones",
                        to="empresa.empresa",
                    ),
                ),
            ],
            options={
                "verbose_name": "liquidación",
                "verbose_name_plural": "liquidaciones",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("empresa", "periodo"),
                        name="unique_liquidacion_por_empresa_periodo",
                    )
                ],
            },
        ),
    ]
