# Generated by Django 5.2.17 on 2026-10-02 21:06

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("concepto", "0001_initial"),
        ("empleado", "0001_initial"),
        ("empresa", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Liquidacion",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("periodo", models.DateField()),
                (
                    "numero",
                    models.PositiveIntegerField(
                        blank=True, default=None, editable=False, null=True
                    ),
                ),
                ("fecha_pago", models.DateField()),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("borrador", "Borrador"),
                            ("en_rectificacion", "En Rectificación"),
                            ("cerrada", "Cerrada"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "tipo_envio",
                    models.CharField(
                        choices=[
                            ("SJ", "SJ (Informar Liquidación)"),
                            ("RE", "RE (Rectificar DJ F931)"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "tipo_liquidacion",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("M", "Mes"),
                            ("Q", "Quincena"),
                            ("D", "Días"),
                            ("H", "Horas"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "domicilio_empresa",
                    models.CharField(
                        editable=False,
                        help_text="Domicilio de la empresa al momento de realizar la liquidación.",
                        max_length=255,
                    ),
                ),
                (
                    "empresa",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="liquidaciones",
                        to="empresa.empresa",
                    ),
                ),
            ],
            options={
                "verbose_name": "liquidación",
                "verbose_name_plural": "liquidaciones",
            },
        ),
        migrations.CreateModel(
            name="LiquidacionEmpleado",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "remunerativo",
                    models.DecimalField(
                        decimal_places=5, default=0, editable=False, max_digits=20
                    ),
                ),
                (
                    "no_remunerativo",
                    models.DecimalField(
                        decimal_places=5, default=0, editable=False, max_digits=20
                    ),
                ),
                (
                    "bruto",
                    models.DecimalField(
                        decimal_places=5, default=0, editable=False, max_digits=20
                    ),
                ),
                (
                    "descuentos",
                    models.DecimalField(
                        decimal_places=5, default=0, editable=False, max_digits=20
                    ),
                ),
                (
                    "neto",
                    models.DecimalField(
                        decimal_places=5, default=0, editable=False, max_digits=20
                    ),
                ),
                (
                    "contribuciones",
                    models.DecimalField(
                        decimal_places=5, default=0, editable=False, max_digits=20
                    ),
                ),
                (
                    "costo_laboral",
                    models.DecimalField(
                        decimal_places=5, default=0, editable=False, max_digits=20
                    ),
                ),
                (
                    "observaciones_recibo",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Observaciones que se reflejaran en el recibo de sueldo",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "observaciones_lsd",
                    models.CharField(
                        blank=True,
                        help_text="Observaciones para Libro de Sueldos Digital de ARCA. Max 80 caracteres.",
                        max_length=80,
                    ),
                ),
                ("fecha_rubrica", models.DateField(blank=True, null=True)),
                (
                    "cantidad_dias_proporcionar_tope",
                    models.PositiveIntegerField(
                        default=0,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(999),
                        ],
                    ),
                ),
                ("codigo_situacion", models.CharField(blank=True, max_length=2)),
                ("codigo_condicion", models.CharField(blank=True, max_length=2)),
                ("codigo_actividad", models.CharField(blank=True, max_length=3)),
                (
                    "codigo_modalidad_contratacion",
                    models.CharField(blank=True, max_length=3),
                ),
                ("codigo_siniestrado", models.CharField(blank=True, max_length=2)),
                ("codigo_localidad", models.CharField(blank=True, max_length=2)),
                (
                    "unidad_tiempo_trabajado",
                    models.CharField(
                        blank=True,
                        choices=[("d", "Días"), ("h", "Horas")],
                        max_length=10,
                        null=True,
                    ),
                ),
                (
                    "tiempo_trabajado",
                    models.PositiveIntegerField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(999),
                        ],
                    ),
                ),
                (
                    "porcentaje_aporte_adicional_ss",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                (
                    "porcentaje_contrib_tarea_diferencial",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                (
                    "cantidad_adherentes_obra_social",
                    models.PositiveIntegerField(
                        default=0,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(99),
                        ],
                    ),
                ),
                (
                    "aporte_adicional_obra_social",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                (
                    "contrib_adicional_obra_social",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                (
                    "base_calc_diferencial_aportes_obra_social_fsr",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                (
                    "base_calc_diferencial_contrib_obra_social_fsr",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                (
                    "base_calc_diferencial_ley_riesgos_trabajo",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                (
                    "remuneracion_maternidad_anses",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                (
                    "base_calc_diferencial_aportes_seg_social",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                (
                    "base_calc_diferencial_contrib_seg_social",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                (
                    "empleado",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="liquidaciones",
                        to="empleado.empleado",
                    ),
                ),
                (
                    "liquidacion",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="empleados",
                        to="liquidacion.liquidacion",
                    ),
                ),
                (
                    "version_empleado",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="liquidaciones",
                        to="empleado.versionempleado",
                    ),
                ),
            ],
            options={
                "verbose_name": "liquidación por empleado",
                "verbose_name_plural": "liquidación por empleado",
            },
        ),
        migrations.CreateModel(
            name="DetalleLiquidacion",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("unidades", models.DecimalField(decimal_places=2, max_digits=12)),
                ("formula_base", models.CharField(max_length=500)),
                (
                    "base",
                    models.DecimalField(
                        decimal_places=5, default=0, editable=False, max_digits=20
                    ),
                ),
                (
                    "importe",
                    models.DecimalField(
                        decimal_places=5,
                        default=0,
                        editable=False,
                        help_text="Unidades * Base",
                        max_digits=20,
                    ),
                ),
                (
                    "cantidad",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                (
                    "unidades_lsd",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("$", "Moneda"),
                            ("%", "Porcentaje"),
                            ("A", "Año"),
                            ("M", "Mes"),
                            ("Q", "Quincena"),
                            ("D", "Días"),
                            ("H", "Horas"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "debito_credito",
                    models.CharField(
                        choices=[("D", "Débito"), ("C", "Crédito")], max_length=10
                    ),
                ),
                ("periodo_ajuste_retroactivo", models.DateField(blank=True, null=True)),
                (
                    "concepto",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="detalles_liquidacion",
                        to="concepto.versionconcepto",
                    ),
                ),
                (
                    "liquidacion_empleado",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="detalles",
                        to="liquidacion.liquidacionempleado",
                    ),
                ),
            ],
            options={
                "verbose_name": "detalle liquidación",
                "verbose_name_plural": "detalles de liquidación",
            },
        ),
        migrations.CreateModel(
            name="TramoSituacionRevista",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("codigo_situacion", models.CharField(blank=True, max_length=2)),
                (
                    "dia_inicio",
                    models.PositiveIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(31),
                        ]
                    ),
                ),
                (
                    "liquidacion_empleado",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="situaciones_revista",
                        to="liquidacion.liquidacionempleado",
                    ),
                ),
            ],
            options={
                "verbose_name": "tramo de situacion de revista",
                "verbose_name_plural": "tramos de situacion de revista",
            },
        ),
        migrations.AddConstraint(
            model_name="liquidacion",
            constraint=models.UniqueConstraint(
                fields=("empresa", "periodo", "numero"),
                name="unique_liquidacion_por_empresa_periodo_numero",
            ),
        ),
        migrations.AddConstraint(
            model_name="liquidacionempleado",
            constraint=models.UniqueConstraint(
                fields=("liquidacion", "empleado"),
                name="unique_empleado_por_liquidacion",
            ),
        ),
        migrations.AddConstraint(
            model_name="detalleliquidacion",
            constraint=models.UniqueConstraint(
                fields=("liquidacion_empleado", "concepto"),
                name="unique_concepto_por_liquidacion_empleado",
            ),
        ),
    ]
