# Generated by Django 5.2.17 on 2026-09-23 14:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("concepto", "0001_initial"),
        ("empleado", "0001_initial"),
        ("empresa", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Liquidacion",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("periodo", models.DateField()),
                ("fecha_pago", models.DateField()),
                (
                    "estado",
                    models.CharField(
                        choices=[("borrador", "Borrador"), ("cerrada", "Cerrada")],
                        editable=False,
                        max_length=30,
                    ),
                ),
                (
                    "domicilio_empresa",
                    models.CharField(
                        editable=False,
                        help_text="Domicilio de la empresa al momento de realizar la liquidación.",
                        max_length=255,
                    ),
                ),
                (
                    "empresa",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="liquidaciones",
                        to="empresa.empresa",
                    ),
                ),
            ],
            options={
                "verbose_name": "liquidación",
                "verbose_name_plural": "liquidaciones",
            },
        ),
        migrations.CreateModel(
            name="LiquidacionEmpleado",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "remunerativo",
                    models.DecimalField(
                        decimal_places=2, default=0, editable=False, max_digits=12
                    ),
                ),
                (
                    "no_remunerativo",
                    models.DecimalField(
                        decimal_places=2, default=0, editable=False, max_digits=12
                    ),
                ),
                (
                    "bruto",
                    models.DecimalField(
                        decimal_places=2, default=0, editable=False, max_digits=12
                    ),
                ),
                (
                    "descuentos",
                    models.DecimalField(
                        decimal_places=2, default=0, editable=False, max_digits=12
                    ),
                ),
                (
                    "neto",
                    models.DecimalField(
                        decimal_places=2, default=0, editable=False, max_digits=12
                    ),
                ),
                (
                    "contribuciones",
                    models.DecimalField(
                        decimal_places=2, default=0, editable=False, max_digits=12
                    ),
                ),
                (
                    "costo_laboral",
                    models.DecimalField(
                        decimal_places=2, default=0, editable=False, max_digits=12
                    ),
                ),
                (
                    "observaciones",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Observaciones que se reflejaran en el recibo de sueldo",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "categoria",
                    models.CharField(
                        blank=True, editable=False, max_length=255, null=True
                    ),
                ),
                (
                    "banco_de_cobro",
                    models.CharField(
                        blank=True, editable=False, max_length=255, null=True
                    ),
                ),
                (
                    "empleado",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="liquidaciones",
                        to="empleado.empleado",
                    ),
                ),
                (
                    "liquidacion",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="empleados",
                        to="liquidacion.liquidacion",
                    ),
                ),
            ],
            options={
                "verbose_name": "liquidación por empleado",
                "verbose_name_plural": "liquidación por empleado",
            },
        ),
        migrations.CreateModel(
            name="DetalleLiquidacion",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("unidades", models.DecimalField(decimal_places=2, max_digits=12)),
                ("formula_base", models.CharField(max_length=500)),
                (
                    "base",
                    models.DecimalField(
                        decimal_places=2, default=0, editable=False, max_digits=12
                    ),
                ),
                (
                    "importe",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        editable=False,
                        help_text="Unidades * Base",
                        max_digits=12,
                    ),
                ),
                (
                    "concepto",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="detalles_liquidacion",
                        to="concepto.versionconcepto",
                    ),
                ),
                (
                    "liquidacion_empleado",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="detalles",
                        to="liquidacion.liquidacionempleado",
                    ),
                ),
            ],
            options={
                "verbose_name": "detalle liquidación",
                "verbose_name_plural": "detalles de liquidación",
            },
        ),
        migrations.AddConstraint(
            model_name="liquidacion",
            constraint=models.UniqueConstraint(
                fields=("empresa", "periodo"),
                name="unique_liquidacion_por_empresa_periodo",
            ),
        ),
        migrations.AddConstraint(
            model_name="liquidacionempleado",
            constraint=models.UniqueConstraint(
                fields=("liquidacion", "empleado"),
                name="unique_empleado_por_liquidacion",
            ),
        ),
        migrations.AddConstraint(
            model_name="detalleliquidacion",
            constraint=models.UniqueConstraint(
                fields=("liquidacion_empleado", "concepto"),
                name="unique_concepto_por_liquidacion_empleado",
            ),
        ),
    ]
