# Generated by Django 5.2.17 on 2026-09-28 23:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("liquidacion", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="detalleliquidacion",
            name="periodo_ajuste_retroactivo",
            field=models.DateField(blank=True, null=True),
        ),
    ]
