# Generated by Django 5.2.17 on 2026-09-24 22:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("liquidacion", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="liquidacionempleado",
            name="detracciones",
            field=models.DecimalField(
                decimal_places=5, default=0, editable=False, max_digits=20
            ),
        ),
        migrations.AddField(
            model_name="liquidacionempleado",
            name="remuneracion_1",
            field=models.DecimalField(
                decimal_places=5, default=0, editable=False, max_digits=20
            ),
        ),
        migrations.AddField(
            model_name="liquidacionempleado",
            name="remuneracion_10",
            field=models.DecimalField(
                decimal_places=5, default=0, editable=False, max_digits=20
            ),
        ),
        migrations.AddField(
            model_name="liquidacionempleado",
            name="remuneracion_2",
            field=models.DecimalField(
                decimal_places=5, default=0, editable=False, max_digits=20
            ),
        ),
        migrations.AddField(
            model_name="liquidacionempleado",
            name="remuneracion_3",
            field=models.DecimalField(
                decimal_places=5, default=0, editable=False, max_digits=20
            ),
        ),
        migrations.AddField(
            model_name="liquidacionempleado",
            name="remuneracion_4",
            field=models.DecimalField(
                decimal_places=5, default=0, editable=False, max_digits=20
            ),
        ),
        migrations.AddField(
            model_name="liquidacionempleado",
            name="remuneracion_5",
            field=models.DecimalField(
                decimal_places=5, default=0, editable=False, max_digits=20
            ),
        ),
        migrations.AddField(
            model_name="liquidacionempleado",
            name="remuneracion_6",
            field=models.DecimalField(
                decimal_places=5, default=0, editable=False, max_digits=20
            ),
        ),
        migrations.AddField(
            model_name="liquidacionempleado",
            name="remuneracion_7",
            field=models.DecimalField(
                decimal_places=5, default=0, editable=False, max_digits=20
            ),
        ),
        migrations.AddField(
            model_name="liquidacionempleado",
            name="remuneracion_8",
            field=models.DecimalField(
                decimal_places=5, default=0, editable=False, max_digits=20
            ),
        ),
        migrations.AddField(
            model_name="liquidacionempleado",
            name="remuneracion_9",
            field=models.DecimalField(
                decimal_places=5, default=0, editable=False, max_digits=20
            ),
        ),
    ]
