# Generated by Django 5.2.17 on 2026-09-22 20:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("liquidacion", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="detalleliquidacion",
            old_name="expresion_base",
            new_name="formula",
        ),
        migrations.RemoveField(
            model_name="detalleliquidacion",
            name="base",
        ),
        migrations.RemoveField(
            model_name="detalleliquidacion",
            name="unidades",
        ),
        migrations.AlterField(
            model_name="detalleliquidacion",
            name="importe",
            field=models.DecimalField(
                decimal_places=2, default=0, editable=False, max_digits=12
            ),
        ),
        migrations.DeleteModel(
            name="ReferenciaDetalle",
        ),
    ]
