# Generated by Django 5.2.17 on 2026-09-20 22:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("liquidacion", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="detalleliquidacion",
            name="base",
            field=models.DecimalField(
                decimal_places=2, default=0, editable=False, max_digits=12
            ),
        ),
        migrations.AlterField(
            model_name="detalleliquidacion",
            name="importe",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                editable=False,
                help_text="Unidades * Base",
                max_digits=12,
            ),
        ),
    ]
