# Generated by Django 5.2.17 on 2026-09-30 18:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("liquidacion", "0002_alter_detalleliquidacion_periodo_ajuste_retroactivo"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="tramosituacionrevista",
            options={
                "verbose_name": "tramo de situacion de revista",
                "verbose_name_plural": "tramos de situacion de revista",
            },
        ),
        migrations.RenameField(
            model_name="liquidacionempleado",
            old_name="observaciones",
            new_name="observaciones_recibo",
        ),
        migrations.RemoveField(
            model_name="liquidacion",
            name="observaciones",
        ),
        migrations.AddField(
            model_name="liquidacionempleado",
            name="observaciones_lsd",
            field=models.CharField(
                blank=True,
                help_text="Observaciones para Libro de Sueldos Digital de ARCA. Max 80 caracteres.",
                max_length=80,
            ),
        ),
        migrations.AddField(
            model_name="tramosituacionrevista",
            name="codigo_situacion",
            field=models.CharField(blank=True, max_length=2),
        ),
        migrations.AlterField(
            model_name="liquidacion",
            name="tipo_envio",
            field=models.CharField(
                choices=[
                    ("SJ", "SJ (Informar Liquidación)"),
                    ("RE", "RE (Rectificar DJ F931)"),
                ],
                max_length=10,
            ),
        ),
    ]
