# Generated by Django 5.2.17 on 2026-09-21 13:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("liquidacion", "0002_alter_detalleliquidacion_base_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="liquidacion",
            name="estado",
            field=models.CharField(
                choices=[("borrador", "Borrador"), ("cerrada", "Cerrada")],
                editable=False,
                max_length=30,
            ),
        ),
    ]
