# Generated by Django 5.2.17 on 2026-09-22 23:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "liquidacion",
            "0002_rename_expresion_base_detalleliquidacion_formula_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="detalleliquidacion",
            name="liquidacion_empleado",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="detalles",
                to="liquidacion.liquidacionempleado",
            ),
        ),
    ]
