# Generated by Django 5.2.17 on 2026-09-25 00:01

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("liquidacion", "0002_liquidacionempleado_detracciones_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="liquidacionempleado",
            name="detracciones",
        ),
        migrations.RemoveField(
            model_name="liquidacionempleado",
            name="remuneracion_1",
        ),
        migrations.RemoveField(
            model_name="liquidacionempleado",
            name="remuneracion_10",
        ),
        migrations.RemoveField(
            model_name="liquidacionempleado",
            name="remuneracion_2",
        ),
        migrations.RemoveField(
            model_name="liquidacionempleado",
            name="remuneracion_3",
        ),
        migrations.RemoveField(
            model_name="liquidacionempleado",
            name="remuneracion_4",
        ),
        migrations.RemoveField(
            model_name="liquidacionempleado",
            name="remuneracion_5",
        ),
        migrations.RemoveField(
            model_name="liquidacionempleado",
            name="remuneracion_6",
        ),
        migrations.RemoveField(
            model_name="liquidacionempleado",
            name="remuneracion_7",
        ),
        migrations.RemoveField(
            model_name="liquidacionempleado",
            name="remuneracion_8",
        ),
        migrations.RemoveField(
            model_name="liquidacionempleado",
            name="remuneracion_9",
        ),
    ]
