# Generated by Django 5.2.17 on 2026-09-23 00:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("liquidacion", "0003_alter_detalleliquidacion_liquidacion_empleado"),
    ]

    operations = [
        migrations.RenameField(
            model_name="detalleliquidacion",
            old_name="formula",
            new_name="formula_base",
        ),
        migrations.AddField(
            model_name="detalleliquidacion",
            name="base",
            field=models.DecimalField(
                decimal_places=2, default=0, editable=False, max_digits=12
            ),
        ),
        migrations.AddField(
            model_name="detalleliquidacion",
            name="unidades",
            field=models.DecimalField(decimal_places=2, default=10, max_digits=12),
        ),
        migrations.AlterField(
            model_name="detalleliquidacion",
            name="importe",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                editable=False,
                help_text="Unidades * Base",
                max_digits=12,
            ),
        ),
    ]
