# Generated by Django 5.2.17 on 2026-09-30 18:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("liquidacion", "0003_alter_tramosituacionrevista_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tramosituacionrevista",
            name="liquidacion_empleado",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="situaciones_revista",
                to="liquidacion.liquidacionempleado",
            ),
        ),
    ]
