# Generated by Django 5.2.17 on 2026-10-02 15:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("liquidacion", "0004_alter_tramosituacionrevista_liquidacion_empleado"),
    ]

    operations = [
        migrations.AlterField(
            model_name="liquidacion",
            name="estado",
            field=models.CharField(
                choices=[
                    ("borrador", "Borrador"),
                    ("en_rectificacion", "En Rectificación"),
                    ("cerrada", "Cerrada"),
                ],
                max_length=30,
            ),
        ),
    ]
