# Generated by Django 5.2.17 on 2026-09-23 00:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("liquidacion", "0004_rename_formula_detalleliquidacion_formula_base_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="detalleliquidacion",
            name="unidades",
            field=models.DecimalField(decimal_places=4, max_digits=12),
        ),
    ]
