# Generated by Django 5.2.17 on 2026-09-23 01:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("liquidacion", "0006_alter_detalleliquidacion_unidades"),
    ]

    operations = [
        migrations.AddField(
            model_name="liquidacionempleado",
            name="observaciones",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Observaciones que se reflejaran en el recibo de sueldo",
                max_length=100,
                null=True,
            ),
        ),
    ]
