# Generated by Django 5.2.17 on 2026-09-28 19:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="GrupoConcepto",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "codigo",
                    models.CharField(
                        help_text="Ej: seguridad_social, inssjp, obra_social, etc",
                        max_length=255,
                        unique=True,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="El código solo puede contener letras minúsculas, números y guiones bajos.",
                                regex="^[a-z0-9_]+$",
                            )
                        ],
                    ),
                ),
                (
                    "denominacion",
                    models.CharField(
                        help_text="Ej: Seguridad Social, INSSJP, Obra Social, etc",
                        max_length=255,
                    ),
                ),
            ],
            options={
                "verbose_name": "grupo para conceptos",
                "verbose_name_plural": "grupos para los conceptos",
            },
        ),
    ]
