# Generated by Django 5.2.17 on 2026-09-20 02:03

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="GrupoConcepto",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "denominacion",
                    models.CharField(
                        editable=False,
                        help_text="Ej: Seguridad Social, INSSJP, Obra Social, etc",
                        max_length=255,
                        unique=True,
                    ),
                ),
            ],
            options={
                "verbose_name": "grupo para conceptos",
                "verbose_name_plural": "grupos para los conceptos",
            },
        ),
    ]
