# Generated by Django 5.2.17 on 2026-09-23 13:47

from django.db import migrations

"""
Esto es importante para crear la composicion de costo laboral
ver: docs/interfaces/recibo_sueldo.md#Composición del costo laboral
"""


GRUPOS_INICIALES = [
    ("sindical", "Sindical"),
    ("seguridad_social", "Seguridad Social"),
    ("obra_social", "Obra Social"),
    ("inssjp", "INSSJP"),
    ("art", "ART"),
    ("scvo", "SCVO"),
]


def crear_grupos(apps, schema_editor):
    GrupoConcepto = apps.get_model(
        "grupo_concepto",
        "GrupoConcepto",
    )

    for codigo, denominacion in GRUPOS_INICIALES:
        GrupoConcepto.objects.get_or_create(
            codigo=codigo,
            defaults={
                "denominacion": denominacion,
            },
        )


class Migration(migrations.Migration):
    dependencies = [
        ("grupo_concepto", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(crear_grupos),
    ]
