# Generated by Django 5.2.17 on 2026-09-24 01:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("concepto", "0001_initial"),
        ("empresa", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="PlantillaLiquidacion",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("denominacion", models.CharField(max_length=255)),
                (
                    "empresa",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="plantillas_liquidacion",
                        to="empresa.empresa",
                    ),
                ),
            ],
            options={
                "verbose_name": "Plantilla para liquidacion",
                "verbose_name_plural": "Plantillas para liquidacion",
            },
        ),
        migrations.CreateModel(
            name="DetallePlantillaLiquidacion",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("unidades", models.DecimalField(decimal_places=2, max_digits=12)),
                ("formula_base", models.CharField(max_length=500)),
                (
                    "concepto",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="detalles_plantillas",
                        to="concepto.concepto",
                    ),
                ),
                (
                    "plantilla",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="detalles",
                        to="plantilla_liquidacion.plantillaliquidacion",
                    ),
                ),
            ],
            options={
                "verbose_name": "Detalle de plantilla para liquidacion",
                "verbose_name_plural": "Detalles de plantilla para liquidacion",
            },
        ),
        migrations.AddConstraint(
            model_name="plantillaliquidacion",
            constraint=models.UniqueConstraint(
                fields=("empresa", "denominacion"), name="unique_plantilla_por_empresa"
            ),
        ),
        migrations.AddConstraint(
            model_name="detalleplantillaliquidacion",
            constraint=models.UniqueConstraint(
                fields=("plantilla", "concepto"), name="unique_concepto_por_plantilla"
            ),
        ),
    ]
