# Generated by Django 5.2.17 on 2026-09-21 14:26

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("plantilla_liquidacion", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="detalleplantillaliquidacion",
            options={
                "verbose_name": "Detalle de plantilla para liquidacion",
                "verbose_name_plural": "Detalles de plantilla para liquidacion",
            },
        ),
        migrations.AlterModelOptions(
            name="plantillaliquidacion",
            options={
                "verbose_name": "Plantilla para liquidacion",
                "verbose_name_plural": "Plantillas para liquidacion",
            },
        ),
    ]
