# Generated by Django 5.2.17 on 2026-10-01 21:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("plantilla_liquidacion", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="detalleplantillaliquidacion",
            name="cantidad",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name="detalleplantillaliquidacion",
            name="debito_credito",
            field=models.CharField(
                choices=[("D", "Débito"), ("C", "Crédito")], default="D", max_length=10
            ),
        ),
        migrations.AddField(
            model_name="detalleplantillaliquidacion",
            name="periodo_ajuste_retroactivo",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="detalleplantillaliquidacion",
            name="unidades_lsd",
            field=models.CharField(
                blank=True,
                choices=[
                    ("$", "Moneda"),
                    ("%", "Porcentaje"),
                    ("A", "Año"),
                    ("M", "Mes"),
                    ("Q", "Quincena"),
                    ("D", "Días"),
                    ("H", "Horas"),
                ],
                max_length=10,
            ),
        ),
    ]
