# Generated by Django 5.2.17 on 2026-09-22 21:08

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("plantilla_liquidacion", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="detalleplantillaliquidacion",
            old_name="expresion_base",
            new_name="formula",
        ),
        migrations.RemoveField(
            model_name="detalleplantillaliquidacion",
            name="unidades",
        ),
    ]
