# Generated by Django 5.2.17 on 2026-09-23 00:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "plantilla_liquidacion",
            "0002_rename_expresion_base_detalleplantillaliquidacion_formula_and_more",
        ),
    ]

    operations = [
        migrations.RenameField(
            model_name="detalleplantillaliquidacion",
            old_name="formula",
            new_name="formula_base",
        ),
        migrations.AddField(
            model_name="detalleplantillaliquidacion",
            name="unidades",
            field=models.DecimalField(decimal_places=2, default=10, max_digits=12),
        ),
    ]
