# Generated by Django 5.2.17 on 2026-10-02 14:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("plantilla_liquidacion", "0002_detalleplantillaliquidacion_cantidad_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="detalleplantillaliquidacion",
            name="debito_credito",
            field=models.CharField(
                choices=[("D", "Débito"), ("C", "Crédito")], max_length=10
            ),
        ),
    ]
