# Generated by Django 5.2.17 on 2026-09-23 00:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "plantilla_liquidacion",
            "0003_rename_formula_detalleplantillaliquidacion_formula_base_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="detalleplantillaliquidacion",
            name="unidades",
            field=models.DecimalField(decimal_places=4, max_digits=12),
        ),
    ]
