# Generated by Django 5.2.17 on 2026-09-23 00:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("plantilla_liquidacion", "0004_alter_detalleplantillaliquidacion_unidades"),
    ]

    operations = [
        migrations.AlterField(
            model_name="detalleplantillaliquidacion",
            name="unidades",
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
    ]
