# Generated by Django 5.2.17 on 2026-10-02 21:06

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="BaseImponible",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "denominacion",
                    models.CharField(editable=False, max_length=100, unique=True),
                ),
                (
                    "identificador",
                    models.CharField(
                        editable=False,
                        max_length=100,
                        unique=True,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="El código solo puede contener letras minúsculas, números y guiones bajos.",
                                regex="^[a-z0-9_]+$",
                            )
                        ],
                    ),
                ),
                (
                    "descripcion",
                    models.CharField(
                        blank=True, default="", editable=False, max_length=500
                    ),
                ),
                ("configurable", models.BooleanField(default=False, editable=False)),
            ],
            options={
                "verbose_name": "base imponible",
                "verbose_name_plural": "bases imponibles",
            },
        ),
        migrations.CreateModel(
            name="ResultadoBaseImponible",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "importe",
                    models.DecimalField(decimal_places=5, default=0, max_digits=20),
                ),
                (
                    "base_imponible",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="resultados",
                        to="base_imponible.baseimponible",
                    ),
                ),
            ],
            options={
                "verbose_name": "Resultado de base imponible",
                "verbose_name_plural": "Resultados de bases imponibles",
                "ordering": ("base_imponible__id",),
            },
        ),
    ]
