# Generated by Django 5.2.17 on 2026-09-24 20:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="BaseImponible",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "denominacion",
                    models.CharField(editable=False, max_length=100, unique=True),
                ),
                (
                    "identificador",
                    models.CharField(
                        editable=False,
                        max_length=100,
                        unique=True,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="El código solo puede contener letras minúsculas, números y guiones bajos.",
                                regex="^[a-z0-9_]+$",
                            )
                        ],
                    ),
                ),
                (
                    "descripcion",
                    models.CharField(
                        blank=True, default="", editable=False, max_length=500
                    ),
                ),
                ("configurable", models.BooleanField(default=False, editable=False)),
            ],
            options={
                "verbose_name": "base imponible",
                "verbose_name_plural": "bases imponibles",
            },
        ),
    ]
