# Generated by Django 5.2.17 on 2026-10-02 21:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("base_imponible", "0001_initial"),
        ("liquidacion", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="resultadobaseimponible",
            name="liquidacion_empleado",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="resultados_bases_imponibles",
                to="liquidacion.liquidacionempleado",
            ),
        ),
        migrations.AddConstraint(
            model_name="resultadobaseimponible",
            constraint=models.UniqueConstraint(
                fields=("liquidacion_empleado", "base_imponible"),
                name="uq_resultado_base_liquidacion_empleado",
            ),
        ),
    ]
