# Generated by Django 5.2.17 on 2026-09-24 20:11

from django.db import migrations

"""
Catálogo de bases imponibles definido por el sistema.

Fuente:
docs/specs_externas/arca_bases_imponibles.md
"""


BASES_IMPONIBLES_INICIALES = [
    ("remuneracion_total", "Remuneración Total", "Remuneración Bruta (remunerativos + no remunerativos)", False),
    ("remuneracion_1", "Remuneración 1", "Base de cálculo para Aportes Previsionales.", True),
    ("remuneracion_2", "Remuneración 2", "Base de cálculo para Contribuciones previsionales e INSSJyP.", True),
    ("remuneracion_3", "Remuneración 3", "Base de cálculo para Contribuciones FNE, asignaciones familiares y "
                                         "RENATRE.", True),
    ("remuneracion_4", "Remuneración 4", "Base de cálculo para Aportes obra social y FSR.", True),
    ("remuneracion_5", "Remuneración 5", "Base de cálculo para Aportes INSSJyP.", True),
    ("remuneracion_6", "Remuneración 6", "Base de cálculo para Aportes diferenciales.", True),
    ("remuneracion_7", "Remuneración 7", "Base de cálculo para Aportes personal regímenes especiales.", True),
    ("remuneracion_8", "Remuneración 8", "Base de cálculo para Contribuciones obra social y FSR.", True),
    ("remuneracion_9", "Remuneración 9", "Base de cálculo para Ley de riesgos de Trabajo (esto se envia a Registro 5, "
                                         "automatico, según cuil).", True),
    ("remuneracion_10", "Remuneración 10", "Remuneración 2 - Detracciones", False),
    ("detracciones", "Detracciones", "Para informar el monto a detraer de la base de contribuciones que va "
                                     "a determinar la base imponible 10.", False),
]


def crear_bases_imponibles(apps, schema_editor):
    BaseImponible = apps.get_model(
        "base_imponible",
        "BaseImponible",
    )

    BaseImponible.objects.bulk_create(
        [
            BaseImponible(
                identificador=identificador,
                denominacion=denominacion,
                descripcion=descripcion,
                configurable=configurable,
            )
            for identificador, denominacion, descripcion, configurable
            in BASES_IMPONIBLES_INICIALES
        ]
    )


class Migration(migrations.Migration):
    dependencies = [
        ("base_imponible", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(crear_bases_imponibles),
    ]
