# Generated by Django 5.2.17 on 2026-09-25 00:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("base_imponible", "0002_crear_bases_imponibles"),
        ("liquidacion", "0003_remove_liquidacionempleado_detracciones_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ResultadoBaseImponible",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "importe",
                    models.DecimalField(decimal_places=5, default=0, max_digits=20),
                ),
                (
                    "base_imponible",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="resultados",
                        to="base_imponible.baseimponible",
                    ),
                ),
                (
                    "liquidacion_empleado",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="resultados_bases_imponibles",
                        to="liquidacion.liquidacionempleado",
                    ),
                ),
            ],
            options={
                "verbose_name": "Resultado de base imponible",
                "verbose_name_plural": "Resultados de bases imponibles",
                "ordering": ("base_imponible__id",),
                "constraints": [
                    models.UniqueConstraint(
                        fields=("liquidacion_empleado", "base_imponible"),
                        name="uq_resultado_base_liquidacion_empleado",
                    )
                ],
            },
        ),
    ]
