# Generated by Django 5.2.17 on 2026-09-20 02:03

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("concepto", "0001_initial"),
        ("grupo_concepto", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="VersionConcepto",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "version",
                    models.PositiveIntegerField(
                        validators=[django.core.validators.MinValueValidator(1)]
                    ),
                ),
                (
                    "denominacion",
                    models.CharField(
                        help_text="Ej: Sueldo Basico, Obra Social, etc", max_length=255
                    ),
                ),
                (
                    "codigo_arca",
                    models.CharField(
                        help_text="Referencia a un concepto de ARCA", max_length=255
                    ),
                ),
                (
                    "categoria",
                    models.CharField(
                        choices=[
                            ("trabajador", "Trabajador"),
                            ("empleador", "Empleador"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("remunerativo", "Remunerativo"),
                            ("no_remunerativo", "No remunerativo"),
                            ("descuento", "Descuento"),
                            ("redondeo", "Redondeo"),
                            ("contribucion", "Contribución"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "unidad",
                    models.CharField(
                        choices=[
                            ("cantidad", "Cantidad"),
                            ("porcentaje", "Porcentaje"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "concepto",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="versiones",
                        to="concepto.concepto",
                    ),
                ),
                (
                    "grupo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="versiones_concepto",
                        to="grupo_concepto.grupoconcepto",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("concepto", "version"),
                        name="unique_version_por_concepto",
                    )
                ],
            },
        ),
    ]
