# Generated by Django 5.2.17 on 2026-09-24 20:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("empresa", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="CategoriaLaboral",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "denominacion",
                    models.CharField(
                        help_text="Ej: Personal de Obra, Administrativo, etc",
                        max_length=255,
                    ),
                ),
                (
                    "empresa",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="categorias_laborales",
                        to="empresa.empresa",
                    ),
                ),
            ],
            options={
                "verbose_name": "categoría laboral",
                "verbose_name_plural": "categorías laborales",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("empresa", "denominacion"),
                        name="unique_categoria_laboral_por_empresa",
                    )
                ],
            },
        ),
    ]
