# Generated by Django 5.2.17 on 2026-10-03 04:01

import concepto.validators
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("base_imponible", "0001_initial"),
        ("empresa", "0001_initial"),
        ("grupo_concepto", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Concepto",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("eliminado", models.BooleanField(default=False)),
                (
                    "empresa",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="conceptos",
                        to="empresa.empresa",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="VersionConcepto",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "version",
                    models.PositiveIntegerField(
                        editable=False,
                        validators=[django.core.validators.MinValueValidator(1)],
                    ),
                ),
                (
                    "denominacion",
                    models.CharField(
                        max_length=255,
                        validators=[concepto.validators.validar_no_remuneracion],
                    ),
                ),
                (
                    "codigo_arca",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=6,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="El código ARCA debe contener exactamente 6 caracteres alfanuméricos.",
                                regex="^[A-Za-z0-9]{6}$",
                            )
                        ],
                    ),
                ),
                (
                    "categoria",
                    models.CharField(
                        choices=[
                            ("trabajador", "Trabajador"),
                            ("empleador", "Empleador"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("remunerativo", "Remunerativo"),
                            ("no_remunerativo", "No remunerativo"),
                            ("descuento", "Descuento"),
                            ("contribucion", "Contribución"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "unidad",
                    models.CharField(
                        choices=[
                            ("cantidad", "Cantidad"),
                            ("porcentaje", "Porcentaje"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "bases_imponibles",
                    models.ManyToManyField(
                        blank=True,
                        related_name="versiones_concepto",
                        to="base_imponible.baseimponible",
                    ),
                ),
                (
                    "concepto",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="versiones",
                        to="concepto.concepto",
                    ),
                ),
                (
                    "grupo",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="versiones_concepto",
                        to="grupo_concepto.grupoconcepto",
                    ),
                ),
            ],
            options={
                "ordering": ("-version",),
                "constraints": [
                    models.UniqueConstraint(
                        fields=("concepto", "version"),
                        name="unique_version_por_concepto",
                    )
                ],
            },
        ),
    ]
