# Generated by Django 5.2.17 on 2026-09-20 02:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("empresa", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Concepto",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "empresa",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="conceptos",
                        to="empresa.empresa",
                    ),
                ),
            ],
        ),
    ]
