# Generated by Django 5.2.17 on 2026-09-24 20:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("base_imponible", "0002_crear_bases_imponibles"),
        ("concepto", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="versionconcepto",
            name="bases_imponibles",
            field=models.ManyToManyField(
                blank=True,
                related_name="versiones_concepto",
                to="base_imponible.baseimponible",
            ),
        ),
    ]
