# Generated by Django 5.2.17 on 2026-09-20 13:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("concepto", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="versionconcepto",
            options={"ordering": ("-version",)},
        ),
        migrations.AddField(
            model_name="concepto",
            name="eliminado",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="versionconcepto",
            name="codigo_arca",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="versionconcepto",
            name="denominacion",
            field=models.CharField(max_length=255),
        ),
    ]
