# Generated by Django 5.2.17 on 2026-09-21 17:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("concepto", "0001_initial"),
        ("grupo_concepto", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="versionconcepto",
            name="grupo",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="versiones_concepto",
                to="grupo_concepto.grupoconcepto",
            ),
        ),
    ]
