# Generated by Django 5.2.17 on 2026-09-20 22:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("concepto", "0002_alter_versionconcepto_options_concepto_eliminado_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="versionconcepto",
            name="codigo_arca",
            field=models.CharField(
                max_length=6,
                validators=[
                    django.core.validators.RegexValidator(
                        message="El código ARCA debe contener exactamente 6 caracteres alfanuméricos.",
                        regex="^[A-Za-z0-9]{6}$",
                    )
                ],
            ),
        ),
    ]
