# Generated by Django 5.2.17 on 2026-09-21 15:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("concepto", "0003_alter_versionconcepto_codigo_arca"),
    ]

    operations = [
        migrations.AlterField(
            model_name="versionconcepto",
            name="concepto",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="versiones",
                to="concepto.concepto",
            ),
        ),
    ]
