# Generated by Django 5.2.17 on 2026-09-20 02:03

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Empresa",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("cuit", models.CharField(editable=False, max_length=11)),
                ("nombre", models.CharField(editable=False, max_length=255)),
                ("domicilio", models.CharField(blank=True, max_length=255)),
            ],
        ),
    ]
