# Generated by Django 5.2.17 on 2026-09-23 14:18

import empleado.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Empresa",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "cuit",
                    models.CharField(
                        max_length=11, validators=[empleado.validators.validar_cuit]
                    ),
                ),
                ("nombre", models.CharField(max_length=255)),
                ("domicilio", models.CharField(blank=True, max_length=255)),
            ],
        ),
    ]
