# Generated by Django 5.2.17 on 2026-10-03 04:01

import core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Empresa",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "cuit",
                    models.CharField(
                        max_length=11, validators=[core.validators.validar_cuit]
                    ),
                ),
                ("nombre", models.CharField(max_length=255)),
                (
                    "tipo_empleador",
                    models.CharField(
                        choices=[
                            ("0", "Administración Pública"),
                            ("1", "Decreto 814/01; Artículo 2, inc B"),
                            ("2", "Servicios Eventuales; Art 2, inc B"),
                            ("4", "Decreto 814/01; Artículo 2, inc A"),
                            ("5", "Servicios Eventuales; Art 2, inc A"),
                            ("7", "Enseñanza Privada"),
                            ("8", "Decreto 1212/03; Clubes AFA"),
                        ],
                        max_length=50,
                    ),
                ),
                ("domicilio", models.CharField(blank=True, max_length=255)),
            ],
        ),
    ]
