# Generated by Django 5.2.17 on 2026-10-02 14:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("empresa", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="empresa",
            name="tipo_empleador",
            field=models.CharField(
                choices=[
                    ("0", "Administración Pública"),
                    ("1", "Decreto 814/01; Artículo 2, inc B"),
                    ("2", "Servicios Eventuales; Art 2, inc B"),
                    ("4", "Decreto 814/01; Artículo 2, inc A"),
                    ("5", "Servicios Eventuales; Art 2, inc A"),
                    ("7", "Enseñanza Privada"),
                    ("8", "Decreto 1212/03; Clubes AFA"),
                ],
                max_length=50,
            ),
        ),
    ]
