# Generated by Django 5.2.17 on 2026-09-20 22:25

import empleado.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("empresa", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="empresa",
            name="cuit",
            field=models.CharField(
                max_length=11, validators=[empleado.validators.validar_cuit]
            ),
        ),
    ]
