# Generated by Django 5.2.17 on 2026-09-20 02:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("liquidacion_empleado", "0001_initial"),
        ("version_concepto", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="DetalleLiquidacion",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("unidades", models.DecimalField(decimal_places=2, max_digits=12)),
                ("base", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "importe",
                    models.DecimalField(
                        decimal_places=2,
                        editable=False,
                        help_text="Unidades * Base",
                        max_digits=12,
                    ),
                ),
                (
                    "concepto",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="detalles_liquidacion",
                        to="version_concepto.versionconcepto",
                    ),
                ),
                (
                    "liquidacion_empleado",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="detalles",
                        to="liquidacion_empleado.liquidacionempleado",
                    ),
                ),
            ],
            options={
                "verbose_name": "detalle liquidación",
                "verbose_name_plural": "detalles de liquidación",
            },
        ),
    ]
