# Generated by Django 5.2.17 on 2026-09-20 02:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("categoria_laboral", "0001_initial"),
        ("empresa", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Empleado",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("dni", models.CharField(editable=False, max_length=8)),
                ("cuil", models.CharField(editable=False, max_length=11)),
                ("apellidos", models.CharField(editable=False, max_length=255)),
                ("nombres", models.CharField(editable=False, max_length=255)),
                ("legajo", models.CharField(editable=False, max_length=50)),
                ("fecha_ingreso", models.DateField(editable=False)),
                (
                    "banco_de_cobro",
                    models.CharField(
                        help_text="Ej: Nacion, Bco. Pcia. BS AS, Santander, etc",
                        max_length=255,
                    ),
                ),
                (
                    "categoria_laboral",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="empleados",
                        to="categoria_laboral.categorialaboral",
                    ),
                ),
                (
                    "empresa",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="empleados",
                        to="empresa.empresa",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("empresa", "legajo"), name="unique_legajo_por_empresa"
                    )
                ],
            },
        ),
    ]
