# Generated by Django 5.2.17 on 2026-09-23 14:18

import datetime
import django.core.validators
import django.db.models.deletion
import empleado.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("categoria_laboral", "0001_initial"),
        ("empresa", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Empleado",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "dni",
                    models.CharField(
                        max_length=8, validators=[empleado.validators.validar_dni]
                    ),
                ),
                (
                    "cuil",
                    models.CharField(
                        max_length=11, validators=[empleado.validators.validar_cuil]
                    ),
                ),
                ("apellidos", models.CharField(max_length=255)),
                ("nombres", models.CharField(max_length=255)),
                ("legajo", models.CharField(max_length=50)),
                (
                    "fecha_ingreso",
                    models.DateField(
                        validators=[
                            django.core.validators.MaxValueValidator(
                                datetime.date(2026, 9, 23),
                                message="La fecha de ingreso no puede ser futura.",
                            )
                        ]
                    ),
                ),
                (
                    "banco_de_cobro",
                    models.CharField(
                        help_text="Ej: Nacion, Bco. Pcia. BS AS, Santander, etc",
                        max_length=255,
                    ),
                ),
                (
                    "categoria_laboral",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="empleados",
                        to="categoria_laboral.categorialaboral",
                    ),
                ),
                (
                    "empresa",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="empleados",
                        to="empresa.empresa",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("empresa", "legajo"), name="unique_legajo_por_empresa"
                    )
                ],
            },
        ),
    ]
