# Generated by Django 5.2.17 on 2026-09-22 20:52

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("empleado", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="empleado",
            name="fecha_ingreso",
            field=models.DateField(
                validators=[
                    django.core.validators.MaxValueValidator(
                        datetime.date(2026, 9, 22),
                        message="La fecha de ingreso no puede ser futura.",
                    )
                ]
            ),
        ),
    ]
