# Generated by Django 5.2.17 on 2026-09-21 13:09

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("empleado", "0002_alter_empleado_cuil_alter_empleado_dni"),
    ]

    operations = [
        migrations.AlterField(
            model_name="empleado",
            name="fecha_ingreso",
            field=models.DateField(
                validators=[
                    django.core.validators.MaxValueValidator(
                        datetime.date(2026, 9, 21),
                        message="La fecha de ingreso no puede ser futura.",
                    )
                ]
            ),
        ),
    ]
